### PR TITLE
Fix Multi Proxy

### PR DESCRIPTION
**Pull request by yario-o**
I just fix Multi proxy support
Now it works perfectly

### CODE REVIEW

**Comment by easyrider81** [comment]
getting this error on on starting feeder and connecting to game:

[ReferenceError: mode is not defined]

and FYI your feeder also throws the error:
<a href="https://gyazo.com/403de50b10be0cb167cd227f2c46c8ba">https://gyazo.com/403de50b10be0cb167cd227f2c46c8ba</a>

Thanks for putting all this work in btw.

**Comment by anonymousxxx02** [comment]
@yario-o i am getting this error `[ReferenceError: mode is not defined]`

**Comment by yario-o** [comment]
@anonymousxxx02 @easyrider81 I fixed these errors check https://github.com/yario-o/slither-feeder-bot/

**Comment by yario-o** [comment]
I do a new PR

**Comment by yario-o** [comment]
https://github.com/l3mpik/slither-feeder-bot/pull/37

**Pull request closed without merging**
